routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PengaduanController;
use App\Http\Controllers\CommentController;

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('commment', 'App\Http\Controllers\CommentController@store')->name('comment');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('pengaduan', PengaduanController::class);
});

app/Models/Pengaduan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengaduan extends Model
{
    use HasFactory;

    protected $fillable = [
        'nik', 'isi_laporan', 'foto', 'status'
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/PengaduanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengaduan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PengaduanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:pengaduan-list|pengaduan-create|pengaduan-edit|pengaduan-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:pengaduan-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:pengaduan-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:pengaduan-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->roles->pluck('name')[0] === 'Admin') {
            $pengaduans =
                Pengaduan::latest()->paginate(5);
        } else {
            $pengaduans =
                Pengaduan::latest()->where('nik', Auth::user()->nik)->paginate(5);
        }

        return view('pengaduan.index', compact('pengaduans'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pengaduan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'isi_laporan' => 'required',
            'foto' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $pengaduan_data = [
            'nik' => Auth::user()->nik,
            'isi_laporan' => $request->input('isi_laporan'),
            'foto' => $request->file('foto')->store('images'),
            'status' => 'belum proses',
        ];

        Pengaduan::create($pengaduan_data);

        return redirect()->route('pengaduan.index')
            ->with('success', 'Pengaduan created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Pengaduan $pengaduan)
    {
        return view('pengaduan.show', compact('pengaduan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengaduan $pengaduan)
    {
        return view('pengaduan.edit', compact('pengaduan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pengaduan $pengaduan)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);

        $pengaduan->update($request->all());

        return redirect()->route('pengaduan.index')
            ->with('success', 'Pengaduan updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengaduan $pengaduan)
    {
        $pengaduan->delete();

        return redirect()->route('pengaduan.index')
            ->with('success', 'Pengaduan deleted successfully');
    }
}

resources/views/pengaduan/commentsDisplay.blade.php
@foreach($comments as $comment)
<div class="display-comment" @if($comment->parent_id != null) style="margin-left:40px;" @endif>
    <div class="chat-content d-inline-block">
        <h5 class="text-muted"><i class="bi bi-circle-fill text-info mx-1"></i> {{ $comment->user->name }}</h5>
        <div class="box mb-2 d-inline-block text-dark rounded p-2 bg-light-info">{{ $comment->comment }}</div>
        <div class="row">
            <div class="col">
                <h6><span></span>  {{ $comment->created_at->diffForHumans();
                    }}</h6>

            </div>
        </div>


    </div>
    <a href="" id="reply"></a>
    <form method="post" action="{{ route('comment') }}">
        @csrf
        <div class="form-group">
            <input type="text" name="comment" class="form-control" />
            <input type="hidden" name="pengaduan_id" value="{{ $pengaduan->id }}" />
            <input type="hidden" name="parent_id" value="{{ $comment->id }}" />
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-warning" value="Reply" />
        </div>
    </form>
    @include('pengaduan.commentsDisplay', ['comments' => $comment->replies])
</div>
@endforeach

resources/views/pengaduan/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">

        <div class="pull-right mb-3">
            <a class="btn btn-primary" href="{{ route('pengaduan.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('pengaduan.store') }}" method="POST" enctype="multipart/form-data">
    @csrf


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group mb-3">
                <strong>Tambahkan Foto</strong>
                <input type="file" name="foto" class="form-control">
            </div>
            <div class="form-group mb-3">
                <strong>Isi Laporan</strong>
                <textarea class="form-control" style="height:150px" name="isi_laporan" placeholder="Detail"></textarea>
            </div>


        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>

@endsection

resources/views/pengaduan/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">

        <div class="pull-right mb-3">
            <a class="btn btn-primary" href="{{ route('pengaduan.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('pengaduan.update',$pengaduan->id) }}" method="POST">
    @csrf
    @method('PUT')


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group mb-3">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $pengaduan->name }}" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group mb-3">
                <strong>Detail:</strong>
                <textarea class="form-control" style="height:150px" name="detail"
                    placeholder="Detail">{{ $pengaduan->detail }}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>
@endsection

resources/views/pengaduan/index.blade.php
@extends('layouts.app')


@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right mb-3">
            @can('pengaduan-create')
            <a class="btn btn-info" href="{{ route('pengaduan.create') }}"><i
                    class="bi bi-exclamation-square-fill mx-1"></i> Create New Pengaduan</a>
            @endcan
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="card ">
    <div class="card-body ">
        <div class="d-md-flex no-block">
            <h4 class="card-title">Users Table</h4>
        </div>
        <div class="table-responsive">
            <table id="file_export"
                class="table stylish-table table-borderless mb-0 mt-2 no-wrap v-middle mb-3 table-hover">
                <thead>
                    <tr class="font-weight-normal text-muted border-bottom">
                        <th>No</th>
                        <th>Images</th>
                        <th>NIK</th>
                        <th>Isi Laporan</th>
                        <th>Date Created</th>
                        <th>Status</th>
                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pengaduans as $pengaduan)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $pengaduan->foto }}"</a>
                        </td>
                        <td>{{ $pengaduan->nik }}</td>
                        <td>{{ $pengaduan->isi_laporan }}</td>
                        <td>{{ $pengaduan->created_at->diffForHumans(); }}</td>
                        <td>{{ $pengaduan->status }}</td>
                        <td>
                            <form action="{{ route('pengaduan.destroy',$pengaduan->id) }}" method="POST">
                                <a class="btn btn-dark btn-circle-lg"
                                    href="{{ route('pengaduan.show',$pengaduan->id) }}"><i
                                        class="bi bi-eye-fill"></i></a>
                                @can('pengaduan-edit')
                                <a class="btn btn-dark btn-circle-lg"
                                    href="{{ route('pengaduan.edit',$pengaduan->id) }}"><i
                                        class="bi bi-pencil-fill"></i></a>
                                @endcan


                                @csrf
                                @method('DELETE')
                                @can('pengaduan-delete')
                                <button type="submit" class="btn btn-dark btn-circle-lg">Delete</button>
                                @endcan
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
</div>


{!! $pengaduans->links() !!}


@endsection

resources/views/pengaduan/show.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">

        <div class="pull-right mb-3">
            <a class="btn btn-info" href="{{ route('pengaduan.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="card py-3">
        <div class="card-body">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image</strong>
                    {{ $pengaduan->foto }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Details:</strong>
                    {{ $pengaduan->isi_laporan }}
                </div>
            </div>
        </div>
    </div>


    <div class="card">
        <div class="card-body">
            @include('pengaduan.commentsDisplay', ['comments' => $pengaduan->comments, 'pengaduan_id' =>
            $pengaduan->id])
            <h5 class="text-muted">Add comment</h5>
            <form method="post" action="{{ route('comment') }}">
                @csrf
                <div class="form-group">
                    <textarea class="form-control" placeholder="Comment" name="comment"></textarea>
                    <input type="hidden" name="pengaduan_id" value="{{ $pengaduan->id }}" />
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-info" value="Comment" />
                </div>
            </form>
        </div>
    </div>
</div>
@endsection